services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse-server
    ports:
      - "8123:8123"  # HTTP接口C:\\TronAddressGen\\output
      - "9000:9000"  # TCP接口
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=wallets
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=123456
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      memlock:
        soft: -1
        hard: -1
    # 超级性能优化
    deploy:
      resources:
        limits:
          memory: 6g
          cpus: '4.0'
    shm_size: 4gb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  clickhouse_data:
    driver: local